<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ApplicationIcon>Assets\emp.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Authors>Sebastian Walter</Authors>
		<Company>evilbaschdi (Sebastian Walter)</Company>
		<Copyright>Copyright © 2025 - $([System.DateTime]::UtcNow.ToString(yyyy)) evilbaschdi</Copyright>
		<!-- ReSharper disable once UnknownProperty -->
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<PackageProjectUrl>https://github.com/evilbaschdi/EvilMediaPlayer</PackageProjectUrl>
		<Product>Evil Media Player</Product>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PublishSingleFile>true</PublishSingleFile>
		<RepositoryUrl>https://github.com/evilbaschdi/EvilMediaPlayer</RepositoryUrl>
		<OutputType>WinExe</OutputType>
		<Nullable>disable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<!--Avalonia doesen't support TrimMode=link currently,but we are working on that https://github.com/AvaloniaUI/Avalonia/issues/6892 -->
		<TrimMode>copyused</TrimMode>
		<TargetFramework>net10.0</TargetFramework>
		<Version>$([System.DateTime]::UtcNow.ToString(yyyy.M.d.H))</Version>
		<RuntimeIdentifier Condition="'$(Configuration)' == 'Debug'">win-x64</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<!--This helps with theme dll-s trimming.
	If you will publish your application in self-contained mode with p:PublishTrimmed=true and it will use Fluent theme Default theme will be trimmed from the output and vice versa.
	https://github.com/AvaloniaUI/Avalonia/issues/5593 -->
		<TrimmableAssembly Include="Avalonia.Themes.Fluent" />
		<TrimmableAssembly Include="Avalonia.Themes.Default" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="EvilBaschdi.About.Avalonia" />
		<PackageReference Include="EvilBaschdi.Core.Avalonia" />
		<PackageReference Include="FluentAvaloniaUI" />
		<PackageReference Include="LibVLCSharp.Avalonia" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="ReactiveUI.Avalonia" />
		<PackageReference Include="TagLibSharp" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Condition="$([MSBuild]::IsOsPlatform('Windows'))" Include="VideoLAN.LibVLC.Windows" />
		<PackageReference Condition="$([MSBuild]::IsOsPlatform('OSX'))" Include="VideoLAN.LibVLC.Mac" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
		<Content Include="Assets\about.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Resource Include="Assets\emp.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\MediaPlayerControl.axaml.cs">
	    <DependentUpon>MediaPlayerControl.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>
</Project>
